<script setup>
import Button from 'primevue/button';
import { useFinanceStore } from '../stores/finance';
const props=defineProps({dashboard:{type:Object,required:true},money:{type:Function,required:true}}); const store=useFinanceStore();
async function addDebt(){const name=prompt('Nombre de la deuda');if(!name)return;const original=Number(prompt('Importe original (€)'));const rate=Number(prompt('Interés nominal anual (%)','0'));await store.addDebt({name,creditor:null,original_amount:Math.round(original*100),outstanding_balance:Math.round(original*100),annual_interest_rate:rate});}
async function addInvestment(){const name=prompt('Nombre de la inversión');if(!name)return;const quantity=Number(prompt('Cantidad','1'));const cost=Number(prompt('Precio medio por unidad (€)','0'));const price=Number(prompt('Precio actual por unidad (€)','0'));await store.addInvestment({name,symbol:null,type:'other',quantity,average_cost:Math.round(cost*100),current_price:Math.round(price*100),currency:props.dashboard.workspace.currency});}
async function pay(debt){const euros=Number(prompt('Cuota pagada (€)'));if(!euros)return;const suggested=Math.min(euros,debt.outstanding_balance/100*Number(debt.annual_interest_rate)/1200);const interest=Number(prompt('Intereses incluidos (€)',suggested.toFixed(2)));const member=props.dashboard.workspace.members[0];await store.payDebt(debt.id,{amount:Math.round(euros*100),interest_amount:Math.round(interest*100),occurred_at:new Date().toLocaleDateString('en-CA'),account_id:props.dashboard.workspace.accounts[0]?.id??null,category_id:null,paid_by_member_id:member?.id??null,description:`Pago ${debt.name}`,notes:null,splits:member?[{member_id:member.id,amount:Math.round(euros*100),percentage:100}]:[]});}
async function increase(debt){const euros=Number(prompt('Capital adicional (€)'));if(!euros||euros<=0)return;const date=prompt('Fecha de la ampliación (AAAA-MM-DD)',new Date().toLocaleDateString('en-CA'));if(!date)return;const description=prompt('Descripción de la ampliación',`Ampliación de ${debt.name}`);if(description===null)return;await store.increaseDebt(debt.id,{amount:Math.round(euros*100),occurred_at:date,description});}
async function removeIncrease(debt,item){if(!confirm(`¿Eliminar la ampliación de ${props.money(item.amount)}?`))return;try{await store.deleteDebtIncrease(debt.id,item.id);}catch(error){alert(error.response?.data?.message??'No se pudo eliminar la ampliación.');}}
</script>
<template><section class="mb-8 grid gap-6 lg:grid-cols-2"><article class="rounded-2xl bg-white p-6 shadow-sm"><div class="mb-5 flex justify-between"><h2 class="text-xl font-bold">Deudas</h2><Button label="Añadir deuda" icon="pi pi-plus" size="small" @click="addDebt"/></div><div v-for="debt in dashboard.workspace.debts" :key="debt.id" class="mb-3 rounded-xl bg-slate-50 p-4"><div class="flex justify-between"><b>{{debt.name}}</b><b>{{money(debt.outstanding_balance)}}</b></div><p class="my-2 text-sm text-slate-500">Interés anual {{debt.annual_interest_rate}} % · Capital total {{money(debt.original_amount)}}</p><div class="flex gap-2"><Button v-if="debt.is_active" label="Registrar pago" size="small" severity="secondary" @click="pay(debt)"/><Button label="Ampliar deuda" size="small" severity="contrast" outlined @click="increase(debt)"/></div><div v-if="debt.increases?.length" class="mt-3 border-t border-slate-200 pt-3"><p class="mb-2 text-xs font-semibold uppercase text-slate-400">Ampliaciones</p><div v-for="item in debt.increases" :key="item.id" class="flex items-center justify-between py-1 text-sm"><span>{{item.occurred_at.slice(0,10)}} · {{item.description || 'Ampliación'}}</span><span class="flex items-center gap-2 font-semibold">+{{money(item.amount)}}<Button icon="pi pi-trash" text rounded size="small" severity="danger" aria-label="Eliminar ampliación" @click="removeIncrease(debt,item)"/></span></div></div></div></article><article class="rounded-2xl bg-white p-6 shadow-sm"><div class="mb-5 flex justify-between"><h2 class="text-xl font-bold">Inversiones</h2><Button label="Añadir inversión" icon="pi pi-plus" size="small" @click="addInvestment"/></div><div v-for="item in dashboard.workspace.investment_positions" :key="item.id" class="mb-3 rounded-xl bg-slate-50 p-4"><div class="flex justify-between"><b>{{item.name}}</b><b>{{money(Math.round(Number(item.quantity)*item.current_price))}}</b></div><p class="text-sm text-slate-500">{{item.quantity}} unidades · Precio medio {{money(item.average_cost)}}</p></div></article></section></template>
